/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Offer = IDL.Record({
  'id' : IDL.Text,
  'sortOrder' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'pieces' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'imageId' : IDL.Opt(IDL.Text),
  'priceCents' : IDL.Nat,
});
export const OffersListResponse = IDL.Record({
  'ok' : IDL.Bool,
  'data' : IDL.Vec(Offer),
  'error' : IDL.Opt(IDL.Text),
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'offerName' : IDL.Text,
  'offerPriceCents' : IDL.Nat,
  'desiredTime' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : IDL.Int,
  'offerPieces' : IDL.Nat,
  'deliveryTypeText' : IDL.Text,
  'pickupAddress' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'statusText' : IDL.Text,
  'offerId' : IDL.Text,
});
export const OrdersListResponse = IDL.Record({
  'ok' : IDL.Bool,
  'data' : IDL.Vec(Order),
  'error' : IDL.Opt(IDL.Text),
});
export const SessionResponse = IDL.Record({
  'ok' : IDL.Bool,
  'token' : IDL.Opt(IDL.Text),
  'error' : IDL.Opt(IDL.Text),
});
export const UploadImageResponse = IDL.Record({
  'ok' : IDL.Bool,
  'error' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'imageId' : IDL.Opt(IDL.Text),
});
export const CreateOrderResponse = IDL.Record({
  'ok' : IDL.Bool,
  'error' : IDL.Opt(IDL.Text),
  'orderId' : IDL.Opt(IDL.Text),
});
export const Settings = IDL.Record({
  'currencySymbol' : IDL.Text,
  'deliveryNote' : IDL.Text,
  'minOrderCents' : IDL.Nat,
  'pickupAddress' : IDL.Text,
  'brandName' : IDL.Text,
  'workHoursText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminCreateOffer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [
        IDL.Record({
          'id' : IDL.Opt(IDL.Text),
          'ok' : IDL.Bool,
          'error' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'adminDeleteOffer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminListOffers' : IDL.Func([IDL.Text], [OffersListResponse], ['query']),
  'adminListOrders' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [OrdersListResponse],
      ['query'],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [SessionResponse], []),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Record({ 'ok' : IDL.Bool })], []),
  'adminSetFeatured' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminSetSortOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminToggleActive' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminUpdateOffer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminUpdateOfferImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminUpdateOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminUpdateSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'adminUploadOfferImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text],
      [UploadImageResponse],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CreateOrderResponse],
      [],
    ),
  'getOfferById' : IDL.Func([IDL.Text], [IDL.Opt(Offer)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'listOffersPublic' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Offer = IDL.Record({
    'id' : IDL.Text,
    'sortOrder' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'pieces' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'imageId' : IDL.Opt(IDL.Text),
    'priceCents' : IDL.Nat,
  });
  const OffersListResponse = IDL.Record({
    'ok' : IDL.Bool,
    'data' : IDL.Vec(Offer),
    'error' : IDL.Opt(IDL.Text),
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'offerName' : IDL.Text,
    'offerPriceCents' : IDL.Nat,
    'desiredTime' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : IDL.Int,
    'offerPieces' : IDL.Nat,
    'deliveryTypeText' : IDL.Text,
    'pickupAddress' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'statusText' : IDL.Text,
    'offerId' : IDL.Text,
  });
  const OrdersListResponse = IDL.Record({
    'ok' : IDL.Bool,
    'data' : IDL.Vec(Order),
    'error' : IDL.Opt(IDL.Text),
  });
  const SessionResponse = IDL.Record({
    'ok' : IDL.Bool,
    'token' : IDL.Opt(IDL.Text),
    'error' : IDL.Opt(IDL.Text),
  });
  const UploadImageResponse = IDL.Record({
    'ok' : IDL.Bool,
    'error' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'imageId' : IDL.Opt(IDL.Text),
  });
  const CreateOrderResponse = IDL.Record({
    'ok' : IDL.Bool,
    'error' : IDL.Opt(IDL.Text),
    'orderId' : IDL.Opt(IDL.Text),
  });
  const Settings = IDL.Record({
    'currencySymbol' : IDL.Text,
    'deliveryNote' : IDL.Text,
    'minOrderCents' : IDL.Nat,
    'pickupAddress' : IDL.Text,
    'brandName' : IDL.Text,
    'workHoursText' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminCreateOffer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [
          IDL.Record({
            'id' : IDL.Opt(IDL.Text),
            'ok' : IDL.Bool,
            'error' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'adminDeleteOffer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminListOffers' : IDL.Func([IDL.Text], [OffersListResponse], ['query']),
    'adminListOrders' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [OrdersListResponse],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [SessionResponse], []),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Record({ 'ok' : IDL.Bool })], []),
    'adminSetFeatured' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminSetSortOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminToggleActive' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminUpdateOffer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminUpdateOfferImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminUpdateOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminUpdateSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'adminUploadOfferImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text],
        [UploadImageResponse],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CreateOrderResponse],
        [],
      ),
    'getOfferById' : IDL.Func([IDL.Text], [IDL.Opt(Offer)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'listOffersPublic' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };