/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateOrderResponse {
  'ok' : boolean,
  'error' : [] | [string],
  'orderId' : [] | [string],
}
export interface Offer {
  'id' : string,
  'sortOrder' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'pieces' : bigint,
  'updatedAt' : bigint,
  'imageUrl' : [] | [string],
  'isFeatured' : boolean,
  'imageId' : [] | [string],
  'priceCents' : bigint,
}
export interface OffersListResponse {
  'ok' : boolean,
  'data' : Array<Offer>,
  'error' : [] | [string],
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'offerName' : string,
  'offerPriceCents' : bigint,
  'desiredTime' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'offerPieces' : bigint,
  'deliveryTypeText' : string,
  'pickupAddress' : string,
  'address' : string,
  'notes' : string,
  'statusText' : string,
  'offerId' : string,
}
export interface OrdersListResponse {
  'ok' : boolean,
  'data' : Array<Order>,
  'error' : [] | [string],
}
export interface SessionResponse {
  'ok' : boolean,
  'token' : [] | [string],
  'error' : [] | [string],
}
export interface Settings {
  'currencySymbol' : string,
  'deliveryNote' : string,
  'minOrderCents' : bigint,
  'pickupAddress' : string,
  'brandName' : string,
  'workHoursText' : string,
}
export interface UploadImageResponse {
  'ok' : boolean,
  'error' : [] | [string],
  'imageUrl' : [] | [string],
  'imageId' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminCreateOffer' : ActorMethod<
    [string, string, bigint, bigint, string],
    { 'id' : [] | [string], 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminDeleteOffer' : ActorMethod<
    [string, string],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminListOffers' : ActorMethod<[string], OffersListResponse>,
  'adminListOrders' : ActorMethod<[string, [] | [string]], OrdersListResponse>,
  'adminLogin' : ActorMethod<[string], SessionResponse>,
  'adminLogout' : ActorMethod<[string], { 'ok' : boolean }>,
  'adminSetFeatured' : ActorMethod<
    [string, string, boolean],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminSetSortOrder' : ActorMethod<
    [string, string, bigint],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminToggleActive' : ActorMethod<
    [string, string, boolean],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminUpdateOffer' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminUpdateOfferImage' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminUpdateOrderStatus' : ActorMethod<
    [string, string, string],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminUpdateSettings' : ActorMethod<
    [string, string, string, string, string, bigint, string],
    { 'ok' : boolean, 'error' : [] | [string] }
  >,
  'adminUploadOfferImage' : ActorMethod<
    [string, string, Uint8Array, string, string],
    UploadImageResponse
  >,
  'createOrder' : ActorMethod<
    [string, string, string, string, string, string, string],
    CreateOrderResponse
  >,
  'getOfferById' : ActorMethod<[string], [] | [Offer]>,
  'getSettings' : ActorMethod<[], Settings>,
  'listOffersPublic' : ActorMethod<[], Array<Offer>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];