/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OrdersListResponse {
    ok: boolean;
    data: Array<Order>;
    error?: string;
}
export interface Settings {
    currencySymbol: string;
    deliveryNote: string;
    email: string;
    minOrderCents: bigint;
    pickupAddress: string;
    brandName: string;
    phone: string;
    workHoursText: string;
}
export interface OffersListResponse {
    ok: boolean;
    data: Array<Offer>;
    error?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Offer {
    id: string;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    pieces: bigint;
    updatedAt: bigint;
    imageUrl?: string;
    isFeatured: boolean;
    imageId?: string;
    priceCents: bigint;
}
export interface CreateOrderResponse {
    ok: boolean;
    error?: string;
    orderId?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SessionResponse {
    ok: boolean;
    token?: string;
    error?: string;
}
export interface Order {
    id: string;
    customerName: string;
    offerName: string;
    offerPriceCents: bigint;
    desiredTime: string;
    customerPhone: string;
    createdAt: bigint;
    offerPieces: bigint;
    deliveryTypeText: string;
    pickupAddress: string;
    address: string;
    notes: string;
    statusText: string;
    offerId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UploadImageResponse {
    ok: boolean;
    error?: string;
    imageUrl?: string;
    imageId?: string;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    adminCreateOffer(token: string, name: string, pieces: bigint, priceCents: bigint, description: string): Promise<{
        id?: string;
        ok: boolean;
        error?: string;
    }>;
    adminDeleteOffer(token: string, id: string): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminListOffers(token: string): Promise<OffersListResponse>;
    adminListOrders(token: string, statusFilter: string | null): Promise<OrdersListResponse>;
    adminLogin(password: string): Promise<SessionResponse>;
    adminLogout(token: string): Promise<{
        ok: boolean;
    }>;
    adminSetFeatured(token: string, id: string, isFeatured: boolean): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminSetSortOrder(token: string, id: string, sortOrder: bigint): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminToggleActive(token: string, id: string, isActive: boolean): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminUpdateOffer(token: string, id: string, name: string, pieces: bigint, priceCents: bigint, description: string): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminUpdateOfferImage(token: string, id: string, imageId: string, imageUrl: string): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminUpdateOrderStatus(token: string, orderId: string, newStatus: string): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminUpdateSettings(token: string, brandName: string, pickupAddress: string, workHoursText: string, deliveryNote: string, minOrderCents: bigint, currencySymbol: string, phone: string, email: string): Promise<{
        ok: boolean;
        error?: string;
    }>;
    adminUploadOfferImage(token: string, offerId: string, imageBytes: Uint8Array, mimeType: string, filename: string): Promise<UploadImageResponse>;
    createOrder(offerId: string, customerPhone: string, customerName: string, deliveryType: string, address: string, desiredTime: string, notes: string): Promise<CreateOrderResponse>;
    getOfferById(id: string): Promise<{
        ok: boolean;
        offer?: Offer;
        error?: string;
    }>;
    getSettings(): Promise<Settings>;
    listOffersPublic(): Promise<{
        ok: boolean;
        data: Array<Offer>;
        error?: string;
    }>;
}
import type { CreateOrderResponse as _CreateOrderResponse, Offer as _Offer, OffersListResponse as _OffersListResponse, Order as _Order, OrdersListResponse as _OrdersListResponse, SessionResponse as _SessionResponse, UploadImageResponse as _UploadImageResponse, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async adminCreateOffer(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<{
        id?: string;
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateOffer(arg0, arg1, arg2, arg3, arg4);
                return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateOffer(arg0, arg1, arg2, arg3, arg4);
            return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteOffer(arg0: string, arg1: string): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteOffer(arg0, arg1);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteOffer(arg0, arg1);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListOffers(arg0: string): Promise<OffersListResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListOffers(arg0);
                return from_candid_OffersListResponse_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListOffers(arg0);
            return from_candid_OffersListResponse_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListOrders(arg0: string, arg1: string | null): Promise<OrdersListResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListOrders(arg0, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_OrdersListResponse_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListOrders(arg0, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_OrdersListResponse_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<SessionResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return from_candid_SessionResponse_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return from_candid_SessionResponse_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<{
        ok: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async adminSetFeatured(arg0: string, arg1: string, arg2: boolean): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetFeatured(arg0, arg1, arg2);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetFeatured(arg0, arg1, arg2);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetSortOrder(arg0: string, arg1: string, arg2: bigint): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSortOrder(arg0, arg1, arg2);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetSortOrder(arg0, arg1, arg2);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminToggleActive(arg0: string, arg1: string, arg2: boolean): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminToggleActive(arg0, arg1, arg2);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminToggleActive(arg0, arg1, arg2);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOffer(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOffer(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOffer(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOfferImage(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOfferImage(arg0, arg1, arg2, arg3);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOfferImage(arg0, arg1, arg2, arg3);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOrderStatus(arg0: string, arg1: string, arg2: string): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderStatus(arg0, arg1, arg2);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderStatus(arg0, arg1, arg2);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateSettings(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string, arg8: string): Promise<{
        ok: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUploadOfferImage(arg0: string, arg1: string, arg2: Uint8Array, arg3: string, arg4: string): Promise<UploadImageResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUploadOfferImage(arg0, arg1, arg2, arg3, arg4);
                return from_candid_UploadImageResponse_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUploadOfferImage(arg0, arg1, arg2, arg3, arg4);
            return from_candid_UploadImageResponse_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<CreateOrderResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_CreateOrderResponse_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_CreateOrderResponse_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfferById(arg0: string): Promise<{
        ok: boolean;
        offer?: Offer;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfferById(arg0);
                return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfferById(arg0);
            return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async listOffersPublic(): Promise<{
        ok: boolean;
        data: Array<Offer>;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listOffersPublic();
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOffersPublic();
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CreateOrderResponse_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateOrderResponse): CreateOrderResponse {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Offer_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Offer): Offer {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OffersListResponse_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OffersListResponse): OffersListResponse {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_OrdersListResponse_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrdersListResponse): OrdersListResponse {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SessionResponse_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionResponse): SessionResponse {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UploadImageResponse_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadImageResponse): UploadImageResponse {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Offer]): Offer | null {
    return value.length === 0 ? null : from_candid_Offer_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    error: [] | [string];
}): {
    ok: boolean;
    error?: string;
} {
    return {
        ok: value.ok,
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    data: Array<_Offer>;
    error: [] | [string];
}): {
    ok: boolean;
    data: Array<Offer>;
    error?: string;
} {
    return {
        ok: value.ok,
        data: from_candid_vec_n13(_uploadFile, _downloadFile, value.data),
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    pieces: bigint;
    updatedAt: bigint;
    imageUrl: [] | [string];
    isFeatured: boolean;
    imageId: [] | [string];
    priceCents: bigint;
}): {
    id: string;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    pieces: bigint;
    updatedAt: bigint;
    imageUrl?: string;
    isFeatured: boolean;
    imageId?: string;
    priceCents: bigint;
} {
    return {
        id: value.id,
        sortOrder: value.sortOrder,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        pieces: value.pieces,
        updatedAt: value.updatedAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageUrl)),
        isFeatured: value.isFeatured,
        imageId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageId)),
        priceCents: value.priceCents
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    data: Array<_Order>;
    error: [] | [string];
}): {
    ok: boolean;
    data: Array<Order>;
    error?: string;
} {
    return {
        ok: value.ok,
        data: value.data,
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    token: [] | [string];
    error: [] | [string];
}): {
    ok: boolean;
    token?: string;
    error?: string;
} {
    return {
        ok: value.ok,
        token: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.token)),
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    error: [] | [string];
    imageUrl: [] | [string];
    imageId: [] | [string];
}): {
    ok: boolean;
    error?: string;
    imageUrl?: string;
    imageId?: string;
} {
    return {
        ok: value.ok,
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        imageUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageUrl)),
        imageId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    error: [] | [string];
    orderId: [] | [string];
}): {
    ok: boolean;
    error?: string;
    orderId?: string;
} {
    return {
        ok: value.ok,
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error)),
        orderId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.orderId))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    offer: [] | [_Offer];
    error: [] | [string];
}): {
    ok: boolean;
    offer?: Offer;
    error?: string;
} {
    return {
        ok: value.ok,
        offer: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.offer)),
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: [] | [string];
    ok: boolean;
    error: [] | [string];
}): {
    id?: string;
    ok: boolean;
    error?: string;
} {
    return {
        id: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.id)),
        ok: value.ok,
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Offer>): Array<Offer> {
    return value.map((x)=>from_candid_Offer_n14(_uploadFile, _downloadFile, x));
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
